import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

interface PageContent { title: string; description: string; icon: string; metrics: Array<{ label: string; value: string; variant: string }>; rows: Array<{ primary: string; secondary: string; status: string; variant: string }>; }

@Component({ selector: 'app-collection-placeholder', templateUrl: './collection-placeholder.component.html', standalone: false })
export class CollectionPlaceholderComponent implements OnInit {
  content!: PageContent;
  breadCrumbItems: Array<{}> = [{ label: 'Waste Collection Operations' }];
  private readonly pages: Record<string, PageContent> = {
    dashboard: { title: 'Waste Collection Dashboard', description: 'Today’s collection activity at a glance.', icon: 'ri-dashboard-2-line', metrics: [{ label: 'Jobs planned', value: '48', variant: 'primary' }, { label: 'Completed', value: '31', variant: 'success' }, { label: 'In progress', value: '12', variant: 'warning' }, { label: 'Missed', value: '5', variant: 'danger' }], rows: [{ primary: 'Route A — Kawempe', secondary: '18 stops · Truck UBA 421C', status: 'In progress', variant: 'warning' }, { primary: 'Route B — Makerere', secondary: '14 stops · Truck UBD 912K', status: 'Completed', variant: 'success' }] },
    'daily-jobs': { title: 'Daily Jobs', description: 'Plan and monitor collection jobs for today.', icon: 'ri-calendar-check-line', metrics: [{ label: 'Assigned', value: '42', variant: 'primary' }, { label: 'Unassigned', value: '6', variant: 'danger' }, { label: 'Completed', value: '31', variant: 'success' }, { label: 'Remaining', value: '11', variant: 'warning' }], rows: [{ primary: 'COL-2026-0901-001', secondary: 'Bwaise Apartments · Route A', status: 'Assigned', variant: 'primary' }, { primary: 'COL-2026-0901-002', secondary: 'Makerere Flats · Route B', status: 'Completed', variant: 'success' }] },
    schedules: { title: 'Schedules', description: 'Recurring collection plans by area and route.', icon: 'ri-calendar-schedule-line', metrics: [{ label: 'Active schedules', value: '18', variant: 'success' }, { label: 'Due today', value: '48', variant: 'primary' }, { label: 'Weekly', value: '14', variant: 'warning' }, { label: 'Monthly', value: '4', variant: 'info' }], rows: [{ primary: 'Kawempe Central — Monday', secondary: 'Route A · Once a week', status: 'Active', variant: 'success' }, { primary: 'Makerere — Tuesday', secondary: 'Route B · Twice a week', status: 'Active', variant: 'success' }] },
    'fleet-crew': { title: 'Fleet & Crew', description: 'Vehicle and crew allocation for collection operations.', icon: 'ri-truck-line', metrics: [{ label: 'Available vehicles', value: '6', variant: 'success' }, { label: 'On route', value: '4', variant: 'primary' }, { label: 'Drivers on duty', value: '8', variant: 'info' }, { label: 'Maintenance', value: '1', variant: 'warning' }], rows: [{ primary: 'UBA 421C — Truck 01', secondary: 'Driver: John · Route A', status: 'On route', variant: 'primary' }, { primary: 'UBD 912K — Truck 02', secondary: 'Driver: Sarah · Route B', status: 'Available', variant: 'success' }] },
    'missed-collections': { title: 'Missed Collections', description: 'Review and resolve customers not collected as planned.', icon: 'ri-error-warning-line', metrics: [{ label: 'Reported today', value: '5', variant: 'danger' }, { label: 'Reassigned', value: '2', variant: 'warning' }, { label: 'Resolved', value: '3', variant: 'success' }, { label: 'Open', value: '2', variant: 'danger' }], rows: [{ primary: 'CUS-00124 — Bwaise Apartments', secondary: 'Route A · Access unavailable', status: 'Open', variant: 'danger' }, { primary: 'CUS-00136 — Kisaasi House', secondary: 'Route B · Rescheduled', status: 'Reassigned', variant: 'warning' }] },
    reports: { title: 'Collection Reports', description: 'Operational summaries and collection performance.', icon: 'ri-file-chart-line', metrics: [{ label: 'Completion rate', value: '89%', variant: 'success' }, { label: 'Collections', value: '1,248', variant: 'primary' }, { label: 'Missed', value: '42', variant: 'danger' }, { label: 'Active routes', value: '12', variant: 'info' }], rows: [{ primary: 'Daily collection performance', secondary: '1 September 2026', status: 'Ready', variant: 'success' }, { primary: 'Route completion report', secondary: 'August 2026', status: 'Ready', variant: 'success' }] }
  };
  constructor(private readonly route: ActivatedRoute) {}
  ngOnInit(): void { this.content = this.pages[this.route.snapshot.data['page']] ?? this.pages['dashboard']; this.breadCrumbItems.push({ label: this.content.title, active: true }); }
}
